clients:
  s3:
    aws_access_key_id: <%= ENV.fetch('AWS_S3_ACCESS_KEY_ID') %>
    aws_secret_access_key: <%= ENV.fetch('AWS_S3_SECRET_ACCESS_KEY') %>
    aws_bucket_name: <%= ENV.fetch('AWS_S3_BUCKET') %>
  twitter:
    consumer_key: <%= ENV.fetch('TWITTER_CONSUMER_KEY', nil) %>
    consumer_secret: <%= ENV.fetch('TWITTER_CONSUMER_SECRET', nil) %>
    bearer_token: <%= ENV.fetch('TWITTER_BEARER_TOKEN', nil) %>
  vision:
    google_application_credentials_path: <%= ENV.fetch('GOOGLE_APPLICATION_CREDENTIALS', nil) %>
    google_application_credentials_json: <%= ENV.fetch('GOOGLE_APPLICATION_CREDENTIALS_JSON', nil) %>
usecase:
  count: <%= ENV.fetch('USECASE_COUNT', 20) %>
  force: <%= ENV.fetch('USECASE_FORCE', false) %>
